/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as ReserveConfirmedRouteImport } from './routes/reserve.confirmed'
import { Route as TourTelAvivRouteImport } from './routes/tour.tel-aviv'
import { Route as TourModiinRouteImport } from './routes/tour.modiin'
import { Route as TourJerusalemRouteImport } from './routes/tour.jerusalem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveConfirmedRoute = ReserveConfirmedRouteImport.update({
  id: '/reserve/confirmed',
  path: '/reserve/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTelAvivRoute = TourTelAvivRouteImport.update({
  id: '/tour/tel-aviv',
  path: '/tour/tel-aviv',
  getParentRoute: () => rootRouteImport,
} as any)
const TourModiinRoute = TourModiinRouteImport.update({
  id: '/tour/modiin',
  path: '/tour/modiin',
  getParentRoute: () => rootRouteImport,
} as any)
const TourJerusalemRoute = TourJerusalemRouteImport.update({
  id: '/tour/jerusalem',
  path: '/tour/jerusalem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reserve': typeof ReserveRoute
  '/reserve/confirmed': typeof ReserveConfirmedRoute
  '/tour/jerusalem': typeof TourJerusalemRoute
  '/tour/modiin': typeof TourModiinRoute
  '/tour/tel-aviv': typeof TourTelAvivRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reserve': typeof ReserveRoute
  '/reserve/confirmed': typeof ReserveConfirmedRoute
  '/tour/jerusalem': typeof TourJerusalemRoute
  '/tour/modiin': typeof TourModiinRoute
  '/tour/tel-aviv': typeof TourTelAvivRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reserve': typeof ReserveRoute
  '/reserve/confirmed': typeof ReserveConfirmedRoute
  '/tour/jerusalem': typeof TourJerusalemRoute
  '/tour/modiin': typeof TourModiinRoute
  '/tour/tel-aviv': typeof TourTelAvivRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reserve' | '/reserve/confirmed' | '/tour/jerusalem' | '/tour/modiin' | '/tour/tel-aviv'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reserve' | '/reserve/confirmed' | '/tour/jerusalem' | '/tour/modiin' | '/tour/tel-aviv'
  id: '__root__' | '/' | '/reserve' | '/reserve/confirmed' | '/tour/jerusalem' | '/tour/modiin' | '/tour/tel-aviv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReserveRoute: typeof ReserveRoute
  ReserveConfirmedRoute: typeof ReserveConfirmedRoute
  TourJerusalemRoute: typeof TourJerusalemRoute
  TourModiinRoute: typeof TourModiinRoute
  TourTelAvivRoute: typeof TourTelAvivRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/confirmed': {
      id: '/reserve/confirmed'
      path: '/reserve/confirmed'
      fullPath: '/reserve/confirmed'
      preLoaderRoute: typeof ReserveConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/tel-aviv': {
      id: '/tour/tel-aviv'
      path: '/tour/tel-aviv'
      fullPath: '/tour/tel-aviv'
      preLoaderRoute: typeof TourTelAvivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/modiin': {
      id: '/tour/modiin'
      path: '/tour/modiin'
      fullPath: '/tour/modiin'
      preLoaderRoute: typeof TourModiinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/jerusalem': {
      id: '/tour/jerusalem'
      path: '/tour/jerusalem'
      fullPath: '/tour/jerusalem'
      preLoaderRoute: typeof TourJerusalemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReserveRoute: ReserveRoute,
  ReserveConfirmedRoute: ReserveConfirmedRoute,
  TourJerusalemRoute: TourJerusalemRoute,
  TourModiinRoute: TourModiinRoute,
  TourTelAvivRoute: TourTelAvivRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
